# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Embla Tech
tagline:          'blog, tech, life, sri lanka'
description:      'Articles and magazine by the staff of Embla Software Innovation'
url:              http://emblatech.github.io
baseurl:          
commentsystem:    disqus
disqus:           embla-tech

author:
  name:           Embla Tech
  url:            https://emblatech.github.io
  email:          geeks@embla.asia

paginate:         9

# Custom vars
icon:             /assets/images/icon.png
cover:            /assets/images/cover.jpg

social:
  # - icon:         twitter
  #   url:          https://twitter.com/iancamporez
  #   desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/emblatech
    desc:         Find us on github

  - icon:         location
    url:          http://embla.asia
    desc:         Embla Software Innovation official site

  # - icon:         googleplus-alt
  #   url:          https://google.com/+IanCamporezBrunelli
  #   desc:         Add me on google+

  # - icon:         feed
  #   url:          http://camporez.github.io/atom.xml
  #   desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  # - title:        About
  #   url:          /about

copyright:
  author:         Embla Software Innovation
  url:            http://emblatech.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  UA-128042194-1

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
